### ISSUE TITLE
很实用的插件👍但还是一些小建议

### ISSUE THREAD

**Issue by Glorenia** [zxhd863943427/siyuan-plugin-memo#3]
虽然看似是很简单的一个插件，但确实大大强化了行内备注的性能，提高了使用效率，非常感谢。

但是想说，有没有可能把 被标注文本的样式 和 思源官方提供的行内备注样式 相统一呢？因为二者在功能指向上本质是相同的，使用者其实不需要基于 被标注文本的样式 来区分哪个是思源自带的行内备注，哪个是块引备注，因为鼠标悬停后，自然就能够区分出来。

如果是使用 现在的样式，整体视觉效果很花&凌乱，比较影响观感，但如果和 行内备注的既有样式 相统一的话，应该可以彻底解决这个问题。（or更高级的解决方案是，将 样式自定义 开放给使用者，但或许可行性较低）

**Comment by zxhd863943427** [comment]
你好，这个插件目前属于只修复bug的状态，不会增加新的功能，但是修改样式在fork代码后应该是很简单的。

如果不想修改代码，也可以用下面的选择器来修改样式：
```css
.protyle-wysiwyg [data-node-id] span[data-type~=block-ref][style*="--memo"]
```
