### ISSUE TITLE
希望能够引述原文再加评论

### ISSUE THREAD

**Issue by LBDOC** [zxhd863943427/siyuan-plugin-memo#4]
非常感谢作者的插件，我们平时看文章，需要随时记录心得体会和感悟的时候，这个插件比官方的ctrl+shift+M的备注好用得多。
想提一个问题：我们做备注评论的时候，一般要知道原文是什么情况，所以可以把原文划线选中的文字通过引述的方式呈现在文末，然后引述下面是个人的备注。就像思源的微信读书插件那种。
目前的方式是，引述里面填写的备注，而没有原文。

**Comment by zxhd863943427** [comment]
finish
