### ISSUE TITLE
原文引用呈现为了双重引用状态

### ISSUE THREAD

**Issue by LBDOC** [zxhd863943427/siyuan-plugin-memo#5]
非常感谢作者的升级，非常棒的功能。
今天使用的时候发现一个问题，引述选中文字原文的时候，在弹出的窗口里面是双重引用状态。也就是原文被引述了，原文下面有一个光标行，此光标行加上面的引述状态的原因一同又处于一个引述状态。  原文引用呈现为了双重引用状态。
这里可否修改为只用一层引述，只引述原文，而光标即书写评论的行为段落块，而不是引用？

**Comment by zxhd863943427** [comment]
目前改为了超级块，备注必须放在一个容器块里，否则无法删除。
